.TH "config" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBline1_param1\fP"
.br
.ti -1c
.RI "double \fBline1_param2\fP"
.br
.ti -1c
.RI "double \fBline1_param3\fP"
.br
.ti -1c
.RI "double \fBline2_param1\fP"
.br
.ti -1c
.RI "double \fBline2_param2\fP"
.br
.ti -1c
.RI "double \fBline2_param3\fP"
.br
.ti -1c
.RI "double \fBinitial_step\fP"
.br
.ti -1c
.RI "bool \fBdynamic_step\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
