.TH "csv_t" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csv_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "int \fBnum_rows\fP"
.br
.ti -1c
.RI "int \fBnum_cols\fP"
.br
.ti -1c
.RI "bool \fBread_flag\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
