.TH "data_t" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnum_rows\fP"
.br
.ti -1c
.RI "int \fBnum_cols\fP"
.br
.ti -1c
.RI "double \fBcoord_original\fP [MAX_LINE_LENGTH][COORDINATE_DIM]"
.br
.ti -1c
.RI "double \fBcoord_pan\fP [MAX_LINE_LENGTH][COORDINATE_DIM]"
.br
.ti -1c
.RI "double \fBcoord_zoom\fP [MAX_LINE_LENGTH][COORDINATE_DIM]"
.br
.ti -1c
.RI "double \fBcoord_rotate\fP [MAX_LINE_LENGTH][COORDINATE_DIM]"
.br
.ti -1c
.RI "float \fBorignal_range\fP [COORDINATE_DIM *2]"
.br
.ti -1c
.RI "float \fBpan_range\fP [COORDINATE_DIM *2]"
.br
.ti -1c
.RI "float \fBpan_diff\fP [COORDINATE_DIM]"
.br
.ti -1c
.RI "float \fBzoom_range\fP [COORDINATE_DIM *2]"
.br
.ti -1c
.RI "float \fBzoom\fP"
.br
.ti -1c
.RI "float \fBrotate_range\fP [COORDINATE_DIM *2]"
.br
.ti -1c
.RI "float \fBrotate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
