.TH "history_t" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
history_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBline\fP [MAX_RECORDS][HASH_STR_LEN]"
.br
.ti -1c
.RI "char \fBhash\fP [MAX_RECORDS][HASH_STR_LEN]"
.br
.ti -1c
.RI "int \fBcategory\fP [MAX_RECORDS]"
.br
.ti -1c
.RI "int \fBcategory_count\fP [MAX_CATEGORY]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
