.TH "input_struct" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input_struct
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float * \fBpX_arr\fP"
.br
.ti -1c
.RI "float * \fBpY_arr\fP"
.br
.ti -1c
.RI "char * \fBtmp_file_1\fP"
.br
.ti -1c
.RI "char * \fBtmp_file_2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
