.TH "intersection" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intersection
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBstep\fP"
.br
.ti -1c
.RI "float \fBy1\fP"
.br
.ti -1c
.RI "float \fBy2\fP"
.br
.ti -1c
.RI "float \fBx1\fP"
.br
.ti -1c
.RI "float \fBx2\fP"
.br
.ti -1c
.RI "float \fBavg_x\fP"
.br
.ti -1c
.RI "float \fBmin_error\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
