.TH "md_hw2_2readme" 3 "Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_hw2_2readme \- Pinky Dimension Distribution 
.PP
 Code is compiled on Windows 11 x64 platform with command:
.PP
.IP "1." 4
\fCmake main ; \&.\\main\&.exe ; make clean_win\fP
.IP "2." 4
\fCpython \&.\\data_gen\&.py ; make test ; \&.\\test\&.exe ; make clean_win\fP
.PP
.SH "Dependencies"
.PP
.IP "1." 4
gcc\&.exe (MinGW-W64 x86_64-ucrt-mcf-seh, built by Brecht Sanders) 13\&.2\&.0
.IP "2." 4
\fCgnuplot 5\&.4 patchlevel 8=>http://www\&.gnuplot\&.info/\fP\&.
.PP
.SH "Directory Structure"
.PP
.IP "1." 4
\fC\&./dataset\fP: contains the dataset data in CSV format\&.
.IP "2." 4
\fC\&./lib\fP: c libraries coded for this project\&.
.IP "3." 4
\fC\&./output\fP: stores the result of this project\&.
.IP "4." 4
\fC\&./data_gen\&.py\fP: generate normal distributed data for algorithm testing and debugging\&.
.IP "5." 4
\fC\&./main\&.c\fP: the entry point of this project\&. Process two set of data at a time and also process merged data and their decision boundary\&.
.IP "6." 4
\fC\&./test\&.c\fP: testing entry point of this project\&. Process only one set of data\&.
.IP "7." 4
\fC\&./makefile\fP: how this project is compiled\&.
.IP "8." 4
\fC\&./readme\&.md\fP: this file you're reading, contains documentations\&.
.PP
.SH "Things to complete"
.PP
.IP "1." 4
Diameter to perimeter conversion\&. 
.PP

