.TH "norm_dist" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
norm_dist
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBmu\fP"
.br
.ti -1c
.RI "float \fBsigma\fP"
.br
.ti -1c
.RI "float \fBintegral_step\fP"
.br
.ti -1c
.RI "float \fBx_min\fP"
.br
.ti -1c
.RI "float \fBx_max\fP"
.br
.ti -1c
.RI "int \fBarr_length\fP"
.br
.ti -1c
.RI "float \fBintegral\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
