.TH "output_format" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
output_format
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBackground\fP"
.br
.ti -1c
.RI "struct \fBForeground\fP"
.br
.ti -1c
.RI "struct \fBStatus\fP"
.br
.ti -1c
.RI "struct \fBStrong_Background\fP"
.br
.ti -1c
.RI "struct \fBStrong_Foreground\fP"
.br
.ti -1c
.RI "struct \fBStyles\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBoutput_format::Styles\fP \fBstyle\fP"
.br
.ti -1c
.RI "struct \fBoutput_format::Foreground\fP \fBforeground\fP"
.br
.ti -1c
.RI "struct \fBoutput_format::Background\fP \fBbackground\fP"
.br
.ti -1c
.RI "struct \fBoutput_format::Strong_Foreground\fP \fBstrong_foreground\fP"
.br
.ti -1c
.RI "struct \fBoutput_format::Strong_Background\fP \fBstrong_background\fP"
.br
.ti -1c
.RI "struct \fBoutput_format::Status\fP \fBstatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
