.TH "output_format::Status" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
output_format::Status
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBsuccess\fP"
.br
.ti -1c
.RI "char * \fBwarning\fP"
.br
.ti -1c
.RI "char * \fBerror\fP"
.br
.ti -1c
.RI "char * \fBpass\fP"
.br
.ti -1c
.RI "char * \fBfail\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
