.TH "output_format::Styles" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
output_format::Styles
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBreset\fP"
.br
.ti -1c
.RI "char * \fBbold\fP"
.br
.ti -1c
.RI "char * \fBunderline\fP"
.br
.ti -1c
.RI "char * \fBinverse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
