.TH "output_format::Strong_Foreground" 3Version 1.0.0" "PRML_Code_Documents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
output_format::Strong_Foreground
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBblack\fP"
.br
.ti -1c
.RI "char * \fBred\fP"
.br
.ti -1c
.RI "char * \fBgreen\fP"
.br
.ti -1c
.RI "char * \fByellow\fP"
.br
.ti -1c
.RI "char * \fBblue\fP"
.br
.ti -1c
.RI "char * \fBmagenta\fP"
.br
.ti -1c
.RI "char * \fBcyan\fP"
.br
.ti -1c
.RI "char * \fBwhite\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PRML_Code_Documents from the source code\&.
